Chat:
    format: "&f<&a%player&f> %message"
Friend:
Guild:
    UpgradePlayerAdd: 2
    UpgradeCost: 30000
    Cost:
        Create: 100000
Bank:
    Sync: Vault
Ware:
    Unlock_Cost: 500
Party:
    Max_Player: 8
Block:
    DisableBreak: true
    UnlimitedResource: true
    ResourceRespawnTime:
        - GOLD_ORE=15
        - IRON_ORE=10
        - DIAMOND_ORE=45
        - COAL_ORE=3
        - REDSTONE_ORE=8
        - LAPIS_ORE=8
        - EMERALD_ORE=120
        - WOOD=5
PressShiftToPickup: true
ActionTips: 
    Pickup: true
    Break: false
    Fight: false
Level: '%lvl^2+%lvl*2'