main: com.vagrantstudio.homelessness.Homelessness
name: Homelessness
version: 1.0.276
softdepend: [Vault, PlayerPoints, PlaceholderAPI, ProtocolLib, MythicMobs, Multiverse-Core]

commands:
    homelessness: